DROP TABLE IF EXISTS studios, actors, reviewers, reviews, films;

CREATE TABLE studios (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  country TEXT NOT NULL
);

CREATE TABLE actors (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  dob TEXT NOT NULL,
  pob TEXT NOT NULL
);

CREATE TABLE reviewers (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  company TEXT NOT NULL
);

CREATE TABLE reviews(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  rating DOUBLE PRECISION CHECK(rating > 0 AND rating < 6) NOT NULL,
  review VARCHAR(140) NOT NULL,
  reviewer_id BIGINT REFERENCES reviewers(id),
  film_id BIGINT
);

CREATE TABLE films (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  studio_id BIGINT REFERENCES studios(id),
  released INT CHECK(released < 3000 AND released > 999) NOT NULL,
  players JSONB NOT NULL
);